# Generated by Django 4.2 on 2025-04-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('subject', 'week', 'lesson')},
        ),
    ]
