# Generated by Django 4.2 on 2025-04-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subjectclass_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creadit_minnum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
